sudo: false

language: go

git:
  depth: 1

install: true

script:
  - chmod +x ./hugo
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  repo: Expost/expost.github.io
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot